### ISSUE TITLE
Python does not build

### ISSUE THREAD

**Issue by justincormack** [rumpkernel/rumprun-packages#25]
Building with current rumprun, built for hw on Ubuntu 1404, I get:

```
rm -f /home/justin/rumprun-packages/python/build/pythondist/share/man/man1/python3.1
(cd /home/justin/rumprun-packages/python/build/pythondist/share/man/man1; ln -s python3.4.1 python3.1)
if test "xupgrade" != "xno"  ; then \
        case upgrade in \
            upgrade) ensurepip="--upgrade" ;; \
            install|*) ensurepip="" ;; \
        esac; \
         _PYTHON_PROJECT_BASE=/home/justin/rumprun-packages/python/build _PYTHON_HOST_PLATFORM=netbsd-x86_64 PYTHONPATH=/home/justin/rumprun-packages/python/build/build/lib.netbsd-x86_64-3.4:./Lib:./Lib/plat-netbsd python3.4 -m ensurepip \
            $ensurepip --root=/ ; \
    fi
Ignoring indexes: https://pypi.python.org/simple
Collecting setuptools
Collecting pip
Installing collected packages: pip, setuptools

  Exception:
  Traceback (most recent call last):
    File "/tmp/tmpfl_g7ofg/pip-6.0.8-py2.py3-none-any.whl/pip/basecommand.py", line 232, in main
      status = self.run(options, args)
    File "/tmp/tmpfl_g7ofg/pip-6.0.8-py2.py3-none-any.whl/pip/commands/install.py", line 347, in run
      root=options.root_path,
    File "/tmp/tmpfl_g7ofg/pip-6.0.8-py2.py3-none-any.whl/pip/req/req_set.py", line 549, in install
      **kwargs
    File "/tmp/tmpfl_g7ofg/pip-6.0.8-py2.py3-none-any.whl/pip/req/req_install.py", line 754, in install
      self.move_wheel_files(self.source_dir, root=root)
    File "/tmp/tmpfl_g7ofg/pip-6.0.8-py2.py3-none-any.whl/pip/req/req_install.py", line 963, in move_wheel_files
      isolated=self.isolated,
    File "/tmp/tmpfl_g7ofg/pip-6.0.8-py2.py3-none-any.whl/pip/wheel.py", line 234, in move_wheel_files
      clobber(source, lib_dir, True)
    File "/tmp/tmpfl_g7ofg/pip-6.0.8-py2.py3-none-any.whl/pip/wheel.py", line 176, in clobber
      os.makedirs(dest)
    File "./Lib/os.py", line 237, in makedirs
      mkdir(name, mode)
  PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.4/site-packages/'

make[1]: Leaving directory `/home/justin/rumprun-packages/python/build'
genisoimage -l -r -o images/stubetc.iso ../stubetc/etc
I: -input-charset not specified, using utf-8 (detected in locale settings)
genisoimage: No such file or directory. Unable to open disc image file 'images/stubetc.iso'.
make: *** [images/stubetc.iso] Error 2
```

**Comment by anttikantee** [comment]
fixed with c963dea
