### ISSUE TITLE
Ruby package build failures

### ISSUE THREAD

**Issue by anttikantee** [rumpkernel/rumprun-packages#89]
There are two errors in the Ruby package build not covered in the README; I'm not sure if I'm doing something wrong or just don't have the prereqs installed on my host.

First one (from `make`):

```
installing default gems:      /var/lib/gems/2.2.0 (build_info, cache, doc, extensions, gems, specifications)
/home/pooka/rumpkernel/rumprun-packages/ruby/build/lib/fileutils.rb:249:in `mkdir': Permission denied @ dir_s_mkdir - /var/lib/gems (Errno::EACCES)
    from /home/pooka/rumpkernel/rumprun-packages/ruby/build/lib/fileutils.rb:249:in `fu_mkdir'
    from /home/pooka/rumpkernel/rumprun-packages/ruby/build/lib/fileutils.rb:226:in `block (2 levels) in mkdir_p'
    from /home/pooka/rumpkernel/rumprun-packages/ruby/build/lib/fileutils.rb:224:in `reverse_each'
    from /home/pooka/rumpkernel/rumprun-packages/ruby/build/lib/fileutils.rb:224:in `block in mkdir_p'
    from /home/pooka/rumpkernel/rumprun-packages/ruby/build/lib/fileutils.rb:210:in `each'
    from /home/pooka/rumpkernel/rumprun-packages/ruby/build/lib/fileutils.rb:210:in `mkdir_p'
    from ./tool/rbinstall.rb:186:in `makedirs'
    from ./tool/rbinstall.rb:293:in `prepare'
    from ./tool/rbinstall.rb:661:in `block in <main>'
    from ./tool/rbinstall.rb:757:in `call'
    from ./tool/rbinstall.rb:757:in `block in <main>'
    from ./tool/rbinstall.rb:754:in `each'
    from ./tool/rbinstall.rb:754:in `<main>'
uncommon.mk:253: recipe for target 'do-install-nodoc' failed
make[1]: *** [do-install-nodoc] Error 1
make[1]: Leaving directory '/home/pooka/rumpkernel/rumprun-packages/ruby/build'
Makefile:18: recipe for target 'build/ruby' failed
make: *** [build/ruby] Error 2
```

Second one (from `make images/examples.iso`):

```
cd examples && bundle install --path=gems
/bin/sh: 1: bundle: not found
Makefile:33: recipe for target 'images/examples.iso' failed
make: *** [images/examples.iso] Error 127
```

**Comment by maniankara** [comment]
First one: Most of us didnt have this problem is because I assume we have been using rvm for local ruby installations which installs ruby, gem(s) etc. under $HOME
However, the problem seems to be here: https://github.com/rumpkernel/rumprun-packages/blob/master/ruby/Makefile#L19
If I were to run the config without "unikernel" options like `./configure --prefix=$SOMEPATH` all good.
I leave it for you unikernel guys to figure out :)

Second one: Most likely, the above fixes this as well.

**Comment by anttikantee** [comment]
Eh, so you are saying that _without_ `--prefix` it does _not_ want to install files to `/var`?

I do remember successfully building and testing the package when @reuben-sutton originally contributed it, so something must have changed.

**Comment by maniankara** [comment]
I haven't tried that, But I meant that, the above `./configure` step (with the --prefix) works with no problem if we have installed ruby (gem) binaries through rvms. This is how it looks on a system which worked out-of-box (Note: GEM PATHS):

```
[anovil@ubuntu-anovil ~]$ which gem
/home/anovil/.rvm/rubies/ruby-2.2.1/bin/gem
[anovil@ubuntu-anovil ~]$ which ruby
/home/anovil/.rvm/rubies/ruby-2.2.1/bin/ruby
[anovil@ubuntu-anovil ~]$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.8
  - RUBY VERSION: 2.2.1 (2015-02-26 patchlevel 85) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/anovil/.rvm/gems/ruby-2.2.1
  - RUBY EXECUTABLE: /home/anovil/.rvm/rubies/ruby-2.2.1/bin/ruby
  - EXECUTABLE DIRECTORY: /home/anovil/.rvm/gems/ruby-2.2.1/bin
  - SPEC CACHE DIRECTORY: /home/anovil/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/anovil/.rvm/rubies/ruby-2.2.1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/anovil/.rvm/gems/ruby-2.2.1
     - /home/anovil/.rvm/gems/ruby-2.2.1@global
  - GEM CONFIGURATION:
...

```

To reproduce your problem, I had to set up a new virtual machine without rvm and install ruby through the system's package manager in which case the `/usr/bin/gem env` would have `/var/lib/gems` (or something like that) as the GEM_PATH's first entry which needs `root` privileges to write into.

**Comment by anttikantee** [comment]
So is the Ruby upstream doing something wrong not fully respecting --prefix?  Or does the ruby guest build always depend on a host ruby (and cannot be sensible patched not to)?

**Comment by reuben-sutton** [comment]
The 2nd example won't ever work, because that requires on having a host ruby install the gems.

I don't think the first issue should be due to not having a working ruby though. I think we've silently been running some ruby script which installs ruby gems to a default dir.

The reason this doesn't explicitly error for others is because the directory it's trying to write to is writeable for the user building - it's normal in the ruby community to have multiple installs in your home directory, so the env variables read will point to that installation.

**Comment by maniankara** [comment]
If you guys havent noticed, "cross compiling" option does differently from normal ruby installations.
I tried comparing the rump-kernel's Makefile and plain ruby Makefile

```
anovil@virtualBox-lubuntu15 ruby-2.3.0]$  diff Makefile ../rumprun-packages/ruby/build/Makefile|grep mini
< MINIRUBY = ./miniruby$(EXEEXT) -I$(srcdir)/lib -I. -I$(EXTOUT)/common\
< PREP          = miniruby$(EXEEXT)
[anovil@virtualBox-lubuntu15 ruby-2.3.0]$  diff Makefile ../rumprun-packages/ruby/build/Makefile|grep -i mini
< MINIRUBY = ./miniruby$(EXEEXT) -I$(srcdir)/lib -I. -I$(EXTOUT)/common\
> MINIRUBY = echo executable host ruby is required.  use --with-baseruby option.; false -I/home/anovil/Work/rumpkernels/rumprun-packages/ruby/build -r$(arch)-fake\
< RUNRUBY_COMMAND = $(MINIRUBY) $(srcdir)/tool/runruby.rb --extout=$(EXTOUT) $(RUNRUBYOPT)
> RUNRUBY_COMMAND = $(MINIRUBY) -I`cd $(srcdir)/lib; pwd`
> XRUBY = $(MINIRUBY)
< BOOTSTRAPRUBY = $(MINIRUBY)
< PREP          = miniruby$(EXEEXT)
[anovil@virtualBox-lubuntu15 ruby-2.3.0]$  

```

Which is because [its different in case of cross compiling](https://github.com/ruby/ruby/blob/trunk/configure.in#L3583)

**Comment by reuben-sutton** [comment]
Thanks.

I guess because it uses miniruby to run all of the build scripts in the
repo but it can't run a cross compiled ruby. I'll add a comment in the
readme that would require a cross-compiled ruby.

**Comment by maniankara** [comment]
Yes.
With enough time spend, I would recommend users to install ruby (and gem) with rvm in the README.
This will also fix Antti's automated builds. What do you guys think? @anttikantee @reuben-sutton ?
I will anyways create a pull request for that.

**Comment by maniankara** [comment]
Hello, I tried getting the rvm build also as a dependent make target (overkill though) and then using that ruby for cross compiling.

```
build/ruby: build/Makefile build/rvm
    (cd build; \
    PATH=$(shell pwd)/build/.rvm/rubies/ruby-2.2.1/bin:$$PATH; \
...
...
build/rvm:
    (export HOME=$(shell pwd)/build; \
    gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3; \
    ../scripts/fetch.sh ${UPSTREAM_RVM} build/install_rvm.sh && cd build && bash install_rvm.sh version latest; \
    source $(shell pwd)/build/.rvm/scripts/rvm && rvm install ruby 2.2.x)

```

Still stuck with some errors

```
...
linking miniruby
addr2line.o: In function `fill_lines':
/home/anovil/Work/rumpkernels/rumprun-packages-maniankara/ruby/build/addr2line.c:569: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
process.o: In function `proc_initgroups':
/home/anovil/Work/rumpkernels/rumprun-packages-maniankara/ruby/build/process.c:5882: warning: Using 'initgroups' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
process.o: In function `obj2gid':
/home/anovil/Work/rumpkernels/rumprun-packages-maniankara/ruby/build/process.c:5079: warning: Using 'getgrnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
file.o: In function `rb_home_dir_of':
/home/anovil/Work/rumpkernels/rumprun-packages-maniankara/ruby/build/file.c:3215: warning: Using 'getpwnam' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/home/anovil/Work/rumpkernels/rumprun-packages-maniankara/ruby/build/file.c:3223: warning: Using 'endpwent' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
process.o: In function `obj2uid':
/home/anovil/Work/rumpkernels/rumprun-packages-maniankara/ruby/build/process.c:5001: warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: dynamic STT_GNU_IFUNC symbol `strcmp' with pointer equality in `/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libc.a(strcmp.o)' can not be used when making an executable; recompile with -fPIE and relink with -pie
collect2: error: ld returned 1 exit status
Makefile:217: recipe for target 'miniruby' failed
make[1]: *** [miniruby] Error 1
...
```
