### ISSUE TITLE
Ruby package - Temporary failure in name resolution (SocketError)

### ISSUE THREAD

**Issue by maniankara** [rumpkernel/rumprun-packages#94]
With the given info in the make file, we get this error:

```
rumprun qemu -g'-nographic -vga none' -i -M 128 -e GEM_HOME=/examples/gems/ruby/2.2.0  -b images/usr.iso,/usr -b images/examples.iso,/examples bin/ruby.bin -I/usr/lib/ruby/2.2.0/ -I/usr/lib/ruby/2.2.0/x86_64-netbsd/ /examples/test_sinatra.rb 
...
...
rumprun: call to ``sigaction'' ignored
rumprun: call to ``_sys___sigprocmask14'' ignored
[2016-03-05 12:57:55] INFO  WEBrick 1.3.1
[2016-03-05 12:57:55] INFO  ruby 2.2.3 (2015-08-18) [x86_64-netbsd]
/usr/lib/ruby/2.2.0/socket.rb:232:in `getaddrinfo': getaddrinfo: Temporary failure in name resolution (SocketError)
    from /usr/lib/ruby/2.2.0/socket.rb:232:in `foreach'
    from /usr/lib/ruby/2.2.0/socket.rb:459:in `tcp_server_sockets'
    from /usr/lib/ruby/2.2.0/webrick/utils.rb:70:in `create_listeners'
    from /usr/lib/ruby/2.2.0/webrick/server.rb:133:in `listen'
    from /usr/lib/ruby/2.2.0/webrick/server.rb:114:in `initialize'
    from /usr/lib/ruby/2.2.0/webrick/httpserver.rb:45:in `initialize'
    from /examples/gems/ruby/2.2.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:31:in `new'
    from /examples/gems/ruby/2.2.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:31:in `run'
    from /examples/gems/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1505:in `start_server'
    from /examples/gems/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1443:in `run!'
    from /examples/gems/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/main.rb:25:in `block in <module:Sinatra>'
```

Re-produceable:
Ubuntu 15.04
Linux ubuntu-anovil 3.19.0-47-generic #53-Ubuntu SMP Mon Jan 18 14:02:48 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by reuben-sutton** [comment]
Hi Anoop,

Thanks for the report. Have you configured networking?

**Comment by maniankara** [comment]
Ha ha, that was a fast reply :) 
Yes, I spend some time enabling networking etc.
Then I figured out that, it just works adding -o param to the end.
I am submitting a pull request about this.
